version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: monthly
    time: "13:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 99
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
    time: "13:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 99
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: monthly
    time: "13:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/assets/"
  schedule:
    interval: monthly
    time: "13:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 99
